//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int Doctor_ID { get; set; }
        public string Name_Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public string Education { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Salary { get; set; }
        public System.DateTime JoiningDate { get; set; }
    }
}
